# Generated by Django 4.2.6 on 2023-12-08 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_emp_empno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salgrade',
            name='grade',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='salgrade',
            name='salary',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
