# Generated by Django 4.2.6 on 2023-12-08 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_salgrade_grade_alter_salgrade_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='salgrade',
            name='comm',
            field=models.IntegerField(default=10000),
        ),
    ]
