# Generated by Django 4.2.6 on 2023-12-08 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_salgrade_comm'),
    ]

    operations = [
        migrations.AddField(
            model_name='emp',
            name='hi',
            field=models.CharField(default='hi', max_length=20),
        ),
    ]
