# Generated by Django 4.2.6 on 2023-12-08 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_emp_hi'),
    ]

    operations = [
        migrations.AddField(
            model_name='emp',
            name='hii',
            field=models.CharField(default=10, max_length=100),
        ),
    ]
