# Generated by Django 4.2.6 on 2023-12-08 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_emp_hii'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emp',
            name='hii',
        ),
    ]
